### ISSUE TITLE
directory.py fails for valid andrew ids

### ISSUE THREAD

**Issue by jez** [ScottyLabs/cmupy#2]
Steps to reproduce the error:

```
$ pip install beautifulsoup4
$ git clone https://github.com/ScottyLabs/cmupy
$ cd cmupy
$ python
Python 2.7.8 (default, Jul  2 2014, 10:14:46)
[GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from directory import Directory
>>> Directory.get_info(andrewid='jezimmer')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "directory.py", line 70, in get_info
    if 'people matched your search criteria' in results.h1.get_text():
AttributeError: 'NoneType' object has no attribute 'h1'
>>>
```

Did something change with the way they render their results pages?
Also, I didn't look too closely at how scraper itself is written, but it seems like the /search/basic/results/ endpoint supports an endpoint of `cmuAndrewId=XXX`, which delivers one result or a "No results" message.

I would take a deeper look at this, but I haven't used BeautifulSoup and the feature I'd like to add using this library is secondary.

**Comment by tomshen** [comment]
This is a sign of a larger issue: we shouldn't be parsing HTML at all but instead access the directory through LDAP.

**Comment by tomshen** [comment]
Closing in favor of #3.
